### ISSUE TITLE
Connectors spec is missing sections 8.6.6+

### ISSUE THREAD

**Issue by lukasj** [jakartaee/specifications#411] opened 2021-07-19 06:49 UTC
https://jakarta.ee/specifications/connectors/2.0/connectors-spec-2.0.html ends by section 8.6.5 but the TOC says the last section is  28.5.5

**Comment by ivargrimstad** [comment] 2021-07-19 07:08
> https://jakarta.ee/specifications/connectors/2.0/connectors-spec-2.0.html ends by section 8.6.5 but the TOC says the last section is 28.5.5

The [PDF](https://jakarta.ee/specifications/connectors/2.0/connectors-spec-2.0.pdf) contains the entire spec, so the issue is with the HTML version.

**Comment by lukasj** [comment] 2021-07-19 07:24
right, PDF is (almost) complete; I'm only missing Related Documents and/or references section there. I believe Specification should have that part.

**Comment by edbratt** [comment] 2021-07-24 02:43
I didn't check the PDF, but if you look at the file that was checked in 
(in the PR <https://github.com/jakartaee/specifications/pull/268>), it's 
complete. I think there is an issue with the post-processing of the file 
when the site is built. I'm not sure what the corrective action should 
be. Maybe the site admins could have a look?

**Closed** 2022-04-12 14:48 UTC
